version: "3"

services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    env_file: "db.env"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    build:  ./db
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    env_file: "db.env"


  nginx:
    build: ./nginx
    depends_on:
      - app
    ports:
      - "8080:80"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@mail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - "10050:80"
